<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'prestashop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '6h2Bm0OIr4TcJcDvdbqZzWmxrOS0F39ISSodT4WNh8geKN8fFKGACGOa');
define('_COOKIE_IV_', 'g7Ve8VkH');
define('_PS_CREATION_DATE_', '2014-08-04');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '0h4kOMJ7UoRIvueRqXfZEOTSewvsxi3E');
define('_RIJNDAEL_IV_', 'aEABDbkknRNMXz/ECHmOag==');
